import "./globals.css";
import { EB_Garamond, Hanken_Grotesk } from "next/font/google";

export const eb_garamond = EB_Garamond({
	subsets: ["latin"],
	variable: "--font-garamond",
});

export const hanken_grotesk = Hanken_Grotesk({
	subsets: ["latin"],
	variable: "--font-grotesk",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${eb_garamond.variable} ${hanken_grotesk.variable} font-garamond bg-orange-100`}
			>
				{children}
			</body>
		</html>
	);
}
